In [ ]:
print('hi')

hi


In [ ]:
import pandas as pd
import numpy as np

data= pd.read_csv("census_income_scikit_label_dataset.csv")

In [ ]:
data.shape

(48842, 15)

In [ ]:
data.head()

age  workclass    fnlwgt  ...  hours_per_week  native_country  income_level
0  39.0        7.0   77516.0  ...            40.0            39.0           0.0
1  50.0        6.0   83311.0  ...            13.0            39.0           0.0
2  38.0        4.0  215646.0  ...            40.0            39.0           0.0
3  53.0        4.0  234721.0  ...            40.0            39.0           0.0
4  28.0        4.0  338409.0  ...            40.0             5.0           0.0

[5 rows x 15 columns]

In [ ]:
data.isnull().sum()

age               0
workclass         0
fnlwgt            0
education         0
education_num     0
marital_status    0
occupation        0
relationship      0
race              0
sex               0
capital_gain      0
capital_loss      0
hours_per_week    0
native_country    0
income_level      0
dtype: int64

In [ ]:
data.columns

Index(['age', 'workclass', 'fnlwgt', 'education', 'education_num',
       'marital_status', 'occupation', 'relationship', 'race', 'sex',
       'capital_gain', 'capital_loss', 'hours_per_week', 'native_country',
       'income_level'],
      dtype='object')

In [ ]:
data['occupation'].unique()

array([ 1.,  4.,  6., 10.,  8., 12.,  3., 14.,  5.,  7., 13.,  0., 11.,
        2.,  9.])

In [ ]:
data['income_level'].unique()

array([0., 1.])

In [ ]:
c=0
c1=0
c2=0
c3=0
c4=0
c5=0
c6=0
c7=0
c8=0
c9=0
c10=0
c11=0
c12=0

for d in data['occupation']:
  if d==0:
    c+=1
  elif d==1:
    c1+=1
  elif d==2:
    c2+=1
  elif d==3:
    c3+=1
  elif d==4:
    c4+=1
  elif d==5:
    c5+=1
  elif d==6:
    c6+=1
  elif d==7:
    c7+=1
  elif d==8:
    c8+=1
  elif d==9:
    c9+=1
  elif d==10:
    c10+=1
  elif d==11:
    c11+=1
  else:
    c12+=1

print(c,c1,c2,c3,c4,c5,c6,c7,c8,c9,c10,c11,c12)

2809 5611 15 6112 6086 1490 2072 3022 4923 242 6172 983 9305


In [ ]:
occupation=['Tech-support', 'Craft-repair',' Other-service', 'Sales', 'Exec-managerial',' Prof-specialty',
     'Handlers-cleaners', 'Machine-op-inspct', 'Adm-clerical', 'Farming-fishing', 
     'Transport-moving', 'Priv-house-serv', 'Protective-serv, Armed-Forces']

13

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x=data[['age','workclass','education','marital_status','occupation','relationship','sex','capital_gain','capital_loss','hours_per_week']]
y=data['income_level']

X_train, X_test, y_train, y_test = train_test_split(x,y,test_size=0.3,random_state=42)

In [ ]:
X_train.shape

(34189, 10)

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
lr= LogisticRegression(solver='saga')
lr.fit(X_train,y_train)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/_sag.py:330: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='saga', tol=0.0001, verbose=0,
                   warm_start=False)

In [ ]:
predic=lr.predict(X_test)
predic

array([0., 0., 0., ..., 0., 0., 0.])

In [ ]:
from sklearn import metrics

In [ ]:
metrics.confusion_matrix(y_test,predic)

array([[10529,   580],
       [ 2498,  1046]])

In [ ]:
print(metrics.classification_report(y_test,predic))

              precision    recall  f1-score   support

         0.0       0.81      0.95      0.87     11109
         1.0       0.64      0.30      0.40      3544

    accuracy                           0.79     14653
   macro avg       0.73      0.62      0.64     14653
weighted avg       0.77      0.79      0.76     14653



In [ ]:
from sklearn.metrics import accuracy_score
print(metrics.accuracy_score(y_test,predic))

0.7899406264928683


In [ ]:
from sklearn.naive_bayes import MultinomialNB

nb= MultinomialNB()
nb.fit(X_train,y_train)
predic1=nb.predict(X_test)
print(metrics.confusion_matrix(y_test,predic1))

[[10711   398]
 [ 2788   756]]


In [ ]:
print(metrics.classification_report(y_test,predic1))

              precision    recall  f1-score   support

         0.0       0.79      0.96      0.87     11109
         1.0       0.66      0.21      0.32      3544

    accuracy                           0.78     14653
   macro avg       0.72      0.59      0.60     14653
weighted avg       0.76      0.78      0.74     14653



In [ ]:
print(metrics.accuracy_score(y_test,predic1))

0.7825701221592848


In [ ]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier()
classifier.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [ ]:
y_pred = classifier.predict(X_test)

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print(confusion_matrix(y_test, y_pred))

[[10259   850]
 [ 1404  2140]]


In [ ]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

         0.0       0.88      0.92      0.90     11109
         1.0       0.72      0.60      0.66      3544

    accuracy                           0.85     14653
   macro avg       0.80      0.76      0.78     14653
weighted avg       0.84      0.85      0.84     14653



In [ ]:
print(accuracy_score(y_test,y_pred))

0.8461748447416911


Decision Tree

In [ ]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier 
from sklearn.model_selection import train_test_split 
from sklearn import metrics